name: lexa
description: A mobile app for managing bills, cards and more financial stuff.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  camera: ^0.10.4
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  intl: ^0.18.0
  path_provider: ^2.0.14
  phosphor_flutter: ^2.0.0
  sqflite: ^2.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/avatars/
    - assets/images/backgrounds/
    - assets/images/categories/
    - assets/images/flags/
    - assets/svgs/branding/
    - assets/svgs/illustrations/
  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro/ReadexPro-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/ReadexPro/ReadexPro-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/ReadexPro/ReadexPro-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/ReadexPro/ReadexPro-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/ReadexPro/ReadexPro-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/ReadexPro/ReadexPro-Bold.ttf
          style: normal
          weight: 700
